### ISSUE TITLE
Remove inappropriate trait implementations

### ISSUE THREAD

**Issue by veldsla** [veldsla/rle_vec#7]
I'm thinking about removing trait implementations that make little sense on a data structure like RleVec.

## Read
Most obvious is `Read`. Except for `read_to_end` this is not a good idea to use. I'm guessing using `to_vec` instead might even be more performant than read_to_end.

## IntoIterator
Also `IntoIterator` needs  to clone the run value for every iteration and is generally not a good idea to use on an RleVec. The naming `Into` implies that you consume the values present and the clone comes 
 as an unexpected performance hit.

What do you @Kerollmops  think?

**Comment by Kerollmops** [comment]
You're right, I think Trait implementations that involve performance hits should not exist or the documentation should be explicit.

**Comment by veldsla** [comment]
Fixed in 449909c
