### ISSUE TITLE
Serialize RleVec?

### ISSUE THREAD

**Issue by dan-da** [veldsla/rle_vec#8]
Would you consider adding serde Serialize/Deserialize support with a serde feature flag?

Otherwise, how to store on disk, transmit over network, etc?

**Comment by veldsla** [comment]
The feature is already available. But you have a point, the documentation doesn't mention it at all!

**Comment by veldsla** [comment]
I updated the readme and published a new patch version to crates.io to reflect the changes. Thanks for reporting.
